apiVersion: v1
kind: ConfigMap
metadata:
  name: client-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://client-database-service:5432/client_db"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "postgres"
  SPRING_JPA_HIBERNATE_DDL-AUTO: "none"
  SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT-SCHEMA: "clients"
  SPRING_LIQUIBASE_CHANGE-LOG: "classpath:db/changelog-master.yml"
  SPRING_LIQUIBASE_ENABLED: "true"
  SPRING_LIQUIBASE_LIQUIBASE-SCHEMA: "public"